version: '3.7'

services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: rukmini12/acad-box:server
    container_name: acad-box-node-server
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    # depends_on:
    #   - serviceName
    # env_file:
    #   - ./backend/.env
    environment:
      - NODE_ENV=production
    networks:
      - app-network
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: rukmini12/acad-box:client
    container_name: acad-box-react-client
    volumes: 
      - ./frontend/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
      - "80:80"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local