name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Backend Docker image
      run: docker build . --file ./backend/Dockerfile --tag acad-box-node-server:$(date +%s)
    - name: Build the Frontend Docker image
      run: docker build . --file ./frontend/Dockerfile --tag acad-box-react-client:$(date +%s)
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/acad-box
